on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
name: Rust tests
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-08-17
          components: rustfmt
          override: true

      - name: Cache rust build
        uses: Swatinem/rust-cache@v2

      - name: Run rust-lang examples
        run: cd rust-lang && cargo run --example generate_examples

      - name: Run tests
        run: cargo test test
